version: '3.1'

services:
    naviserver:
        image: sussdorff/project-open:oacs-5-10
        volumes:
            - content:/var/www/openacs/content-repository-content-files
            - filestorage:/var/www/openacs/filestorage
            - ./migration:/var/www/openacs/www/migration
            
        depends_on: 
            - postgres
        ports: 
            - 8080:8000
        environment:
            - NS_DEBUG=false
            - POSTGRES_PASSWORD=testing
            - NS_verboseSQL=false
            - NS_DEV=false

    postgres:
        image: postgres:9
        environment: 
            - POSTGRES_PASSWORD=testing
            - POSTGRES_USER=openacs
            - POSTGRES_DB=openacs
        ports: 
            - 5432:5432
        volumes:
            - data:/var/lib/postgresql/data
            - ./database:/docker-entrypoint-initdb.d

    unoserver:
        image: alphakevin/unoconv-server

volumes:
    data:
    content:
    filestorage:
    
        
    