version: '3.1'

services:
    naviserver:
        image: sussdorff/project-open
        volumes:
            - content:/var/www/openacs/content-repository-content-files
            - filestorage:/var/www/openacs/filestorage
            - ./migration:/var/www/openacs/www/migration
            
        depends_on: 
            - postgres
        ports: 
            - 8080:8000

        secrets:
            - psql_password
            - psql_user
            - config_vars
        restart: always

    postgres:
        image: postgres:14
        secrets:
            - psql_password
            - psql_user
        command: postgres -c shared_buffers=512MB -c effective_cache_size=1024MB -c work_mem=16MB
        environment: 
            POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
            POSTGRES_USER_FILE: /run/secrets/psql_user
            POSTGRES_DB: openacs
        volumes:
            - data:/var/lib/postgresql/data
            - ./database:/docker-entrypoint-initdb.d
        restart: always
    libreoffice:
        image: sussdorff/libreoffice
        volumes:
            - ./libreoffice-config.yml:/app/config.yml
        restart: always
volumes:
    data:
    content:
    filestorage:
    
        
secrets:
    psql_user:
        file: ./psql_user.txt
    psql_password:
        file: ./psql_password.txt    
    config_vars:
        file: ./config_vars.tcl